export const zones = [
  { value: 'zone1', label: 'Select Your Zone' },
  { value: 'zone2', label: 'CE Aba Zone' },
  { value: 'zone3', label: 'CE Accra Zone' },
  { value: 'zone4', label: 'CE Abuja Zone 1' },
  { value: 'zone5', label: 'CE Abuja Zone 2' },
  { value: 'zone6', label: 'CE Amsterdam' },
  { value: 'zone7', label: 'CE Australia Zone' },
  { value: 'zone8', label: 'CE Benin Zone 1' },
  { value: 'zone9', label: 'CE Benin Zone 2' },
  { value: 'zone10', label: 'CE Toronto Zone' },
  { value: 'zone11', label: 'CE Caetown Zone 1' },
  { value: 'zone12', label: 'CE Caetown Zone 2' },
  { value: 'zone13', label: 'CE Chad' },
  { value: 'zone14', label: 'CE Dallas Zone' },
  { value: 'zone15', label: 'CE Durban Zone' },
  { value: 'zone16', label: 'CE Eastern Europe Region' },
  { value: 'zone17', label: 'CE East Asia Region' },
  { value: 'zone18', label: 'CE Edo North & Central Zone' },
  { value: 'zone19', label: 'CE EWCA Zone 1' },
  { value: 'zone20', label: 'CE EWCA Zone 2' },
  { value: 'zone21', label: 'CE EWCA Zone 3' },
  { value: 'zone22', label: 'CE EWCA Zone 4' },
  { value: 'zone23', label: 'CE EWCA Zone 5' },
  { value: 'zone24', label: 'CE EWCA Zone 6' },
  { value: 'zone25', label: 'CE Ibadan Zone 1' },
  { value: 'zone26', label: 'CE Ibadan Zone 2' },
  { value: 'zone17', label: 'CE India Zone' },
  { value: 'zone28', label: 'CE Kenya Zone' },
  { value: 'zone29', label: 'CE Lagos Virtual Zone' },
  { value: 'zone30', label: 'CE Lagos Zone 1' },
  { value: 'zone31', label: 'CE Lagos Zone 2' },
  { value: 'zone32', label: 'CE Lagos Zone 3' },
  { value: 'zone33', label: 'CE Lagos Zone 4' },
  { value: 'zone34', label: 'CE Lagos Zone 5' },
  { value: 'zone35', label: 'CE Lagos Zone 6' },
  { value: 'zone36', label: 'CE Lagos Sub Zone A' },
  { value: 'zone37', label: 'CE Lagos Sub Zone B' },
  { value: 'zone38', label: 'CE Lagos Sub Zone C' },
  { value: 'zone39', label: 'CE Loveworld Church Zone' },
  { value: 'zone40', label: 'CE Onitsha Zone' },
  { value: 'zone41', label: 'CE Middle East & South East Asia Region' },
  { value: 'zone42', label: 'CE Ministry Center Abuja' },
  { value: 'zone43', label: 'CE Ministry Center Abeokuta' },
  { value: 'zone44', label: 'CE Ministry Center Calabar' },
  { value: 'zone45', label: 'CE Ministry Center Ibadan' },
  { value: 'zone46', label: 'CE Ministry Center Warri' },
  { value: 'zone47', label: 'CE Mid West Zone' },
  { value: 'zone48', label: 'CE Nigeria North East Zone 1' },
  { value: 'zone49', label: 'CE Nigeria North West Zone 1' },
  { value: 'zone50', label: 'CE Nigeria North West Zone 2' },
  { value: 'zone51', label: 'CE North Central Zone 1' },
  { value: 'zone52', label: 'CE North CentralZone 2' },
  { value: 'zone53', label: 'CE South South Zone 1' },
  { value: 'zone54', label: 'CE South South Zone 2' },
  { value: 'zone7', label: 'CE South South Zone 3' },
  { value: 'zone53', label: 'CE South West Zone 1' },
  { value: 'zone54', label: 'CE South West Zone 2' },
  { value: 'zone7', label: 'CE South West Zone 3' },
  { value: 'zone53', label: 'CE South West Zone 4' },
  { value: 'zone54', label: 'CE South West Zone 5' },
  { value: 'zone7', label: 'CE South East Zone 1' },
  { value: 'zone53', label: 'CE South East Zone 2' },
  { value: 'zone54', label: 'CE South East Zone 3' },
  { value: 'zone7', label: 'CE Northern Region 1 Zone 2' },
  { value: 'zone53', label: 'CE Nothern Region 2' },
  { value: 'zone54', label: 'CE Ottawa Zone' },
  { value: 'zone7', label: 'CE Onitsha Zone' },
  { value: 'zone54', label: 'CE Port Harcourt Zone 1' },
  { value: 'zone7', label: 'CE Port Harcourt Zone 2' },
  { value: 'zone54', label: 'CE Port Harcourt Zone 3' },
  { value: 'zone7', label: 'CE Quebec Zone' },
  { value: 'zone54', label: 'CE South America Region' },
  { value: 'zone7', label: 'CE SA Zone 1' },
  { value: 'zone54', label: 'CE SA Zone 2' },
  { value: 'zone7', label: 'CE SA Zone 3' },
  { value: 'zone54', label: 'CE SA Zone 4' },
  { value: 'zone7', label: 'CE SA Zone 5' },
  { value: 'zone54', label: 'CE South America Region' },
  { value: 'zone7', label: 'CE South America, New Zealand And Pacific Islands Region' },
  { value: 'zone54', label: 'CE USA Zone 1 (Region 1)' },
  { value: 'zone7', label: 'CE USA Zone 2 (Region 1)' },
  { value: 'zone54', label: 'CE USA Zone 2 (Region 2)' },
  { value: 'zone54', label: 'CE USA Region 3' },
  { value: 'zone54', label: 'CE UK Zone 1 (UK Region 1)' },
  { value: 'zone54', label: 'CE UK Zone 1 (UK Region 2)' },
  { value: 'zone54', label: 'CE UK Zone 2 (UK Region 1)' },
  { value: 'zone54', label: 'CE UK Zone 3 (UK Region 1)' },
  { value: 'zone54', label: 'CE UK Zone 3 (UK Region 2)' },
  { value: 'zone54', label: 'CE UK Zone 4 (UK Region 1)' },
  { value: 'zone54', label: 'CE UK Zone 4 (UK Region 2)' },
  { value: 'zone54', label: 'CE Western Euurope Zone 1' },
  { value: 'zone54', label: 'CE Western Europe Zone 2' },
  { value: 'zone54', label: 'CE Western Europe Zone 3' },
  { value: 'zone54', label: 'CE Western Europe Zone 4' },
  { value: 'zone54', label: 'CE Warri DSC Sub Zone' },
  { value: 'zone54', label: 'CE BLW Capmus Ministry Europe Region' },
  { value: 'zone54', label: 'BLW Capmus Ministry Nigeria Region' },
  { value: 'zone54', label: 'BLW Capmus Ministry Southern Africa Region' },
  { value: 'zone54', label: 'BLW Capmus Ministry West Africa Region' },
  { value: 'zone54', label: 'BLW Capmus Ministry MIddle East & North Africa Region' },
  { value: 'zone54', label: 'BLW Camus Ministry East & Central Africa Region' },
  { value: 'zone54', label: 'BLW Campus Ministry USA Region 1' },
  { value: 'zone54', label: 'BLW Campus Ministry USA Region 2' },
  { value: 'zone54', label: 'BLW Campus Ministry Canada-Sub Region' }
];